-- ezdoc-spec DDL: postgres
-- Generated by ezdoc/cli/spec-dump.php from migrations/blueprints/
-- DO NOT EDIT — regenerate via `php cli/spec-dump.php`

-- Table: ezdoc_audit_log
CREATE TABLE "ezdoc_audit_log" (
  "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  "event_type" VARCHAR(64) NOT NULL,
  "event_uuid" UUID,
  "actor_id" BIGINT,
  "actor_roles" VARCHAR(255),
  "actor_type" TEXT NOT NULL DEFAULT 'user' CHECK ("actor_type" IN ('user', 'system', 'public', 'api')),
  "target_type" VARCHAR(32),
  "target_id" VARCHAR(64),
  "template_id" BIGINT,
  "doc_id" BIGINT,
  "ip_address" VARCHAR(45),
  "user_agent" TEXT,
  "request_id" UUID,
  "session_id" VARCHAR(64),
  "trace_id" UUID,
  "previous_value" JSONB,
  "new_value" JSONB,
  "metadata" JSONB,
  "result" TEXT NOT NULL DEFAULT 'success' CHECK ("result" IN ('success', 'denied', 'error', 'warning')),
  "message" TEXT,
  "occurred_at" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
COMMENT ON TABLE "ezdoc_audit_log" IS 'Audit log untuk compliance + event sourcing (append-only)';
COMMENT ON COLUMN "ezdoc_audit_log"."event_type" IS 'e.g. doc.created, template.saved, authz.denied';
COMMENT ON COLUMN "ezdoc_audit_log"."event_uuid" IS 'UUID v7 untuk correlate cross-system';
COMMENT ON COLUMN "ezdoc_audit_log"."actor_id" IS 'id_pegawai/user (NULL untuk public/system)';
COMMENT ON COLUMN "ezdoc_audit_log"."actor_roles" IS 'Snapshot roles saat event';
COMMENT ON COLUMN "ezdoc_audit_log"."target_type" IS 'template | document | signature | verification';
COMMENT ON COLUMN "ezdoc_audit_log"."target_id" IS 'ID target (bisa non-int untuk slug/uuid)';
COMMENT ON COLUMN "ezdoc_audit_log"."ip_address" IS 'IPv4 or IPv6';
COMMENT ON COLUMN "ezdoc_audit_log"."request_id" IS 'UUID v7 untuk correlate events per HTTP request';
COMMENT ON COLUMN "ezdoc_audit_log"."session_id" IS 'Session identifier untuk timeline user';
COMMENT ON COLUMN "ezdoc_audit_log"."trace_id" IS 'Distributed tracing (OpenTelemetry compatible)';
COMMENT ON COLUMN "ezdoc_audit_log"."previous_value" IS 'State sebelum change';
COMMENT ON COLUMN "ezdoc_audit_log"."new_value" IS 'State setelah change';
COMMENT ON COLUMN "ezdoc_audit_log"."metadata" IS 'Context-specific per event type';
COMMENT ON COLUMN "ezdoc_audit_log"."message" IS 'Human-readable summary';
COMMENT ON COLUMN "ezdoc_audit_log"."occurred_at" IS 'Event timestamp';
CREATE INDEX "idx_event_time" ON "ezdoc_audit_log" ("event_type", "occurred_at");
CREATE INDEX "idx_actor_time" ON "ezdoc_audit_log" ("actor_id", "occurred_at");
CREATE INDEX "idx_target" ON "ezdoc_audit_log" ("target_type", "target_id");
CREATE INDEX "idx_template_time" ON "ezdoc_audit_log" ("template_id", "occurred_at");
CREATE INDEX "idx_doc_time" ON "ezdoc_audit_log" ("doc_id", "occurred_at");
CREATE INDEX "idx_time" ON "ezdoc_audit_log" ("occurred_at");
CREATE INDEX "idx_result_time" ON "ezdoc_audit_log" ("result", "occurred_at");
CREATE INDEX "idx_request" ON "ezdoc_audit_log" ("request_id");
CREATE INDEX "idx_session" ON "ezdoc_audit_log" ("session_id");
CREATE INDEX "idx_trace" ON "ezdoc_audit_log" ("trace_id");

-- Table: ezdoc_default_vars
CREATE TABLE "ezdoc_default_vars" (
  "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  "var_name" VARCHAR(100) NOT NULL,
  "description" VARCHAR(255),
  "is_enabled" BOOLEAN NOT NULL DEFAULT TRUE,
  "metadata" JSONB,
  "created_at" TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uniq_ezdoc_default_vars_var_name" UNIQUE ("var_name")
);
COMMENT ON TABLE "ezdoc_default_vars" IS 'Whitelist default variables untuk template placeholder';
COMMENT ON COLUMN "ezdoc_default_vars"."is_enabled" IS 'Soft-disable tanpa delete';
COMMENT ON COLUMN "ezdoc_default_vars"."metadata" IS 'Extensibility';
CREATE INDEX "idx_enabled" ON "ezdoc_default_vars" ("is_enabled");

-- Table: ezdoc_documents
CREATE TABLE "ezdoc_documents" (
  "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  "uuid" UUID NOT NULL,
  "template_id" BIGINT NOT NULL,
  "template_uuid" UUID NOT NULL,
  "template_version" INTEGER NOT NULL DEFAULT 1,
  "title" VARCHAR(255),
  "norm" VARCHAR(50),
  "nopen" VARCHAR(50),
  "label" VARCHAR(100) NOT NULL DEFAULT '-',
  "version" INTEGER NOT NULL DEFAULT 1,
  "field_values" JSONB,
  "signature_values" JSONB,
  "metadata" JSONB,
  "status" TEXT NOT NULL DEFAULT 'published' CHECK ("status" IN ('draft', 'published', 'locked', 'archived')),
  "is_locked" BOOLEAN NOT NULL DEFAULT FALSE,
  "content_hash" VARCHAR(64),
  "content_hash_at" TIMESTAMP(6) WITHOUT TIME ZONE,
  "content_hash_version" INTEGER,
  "public_slug" VARCHAR(32),
  "public_slug_active" BOOLEAN NOT NULL DEFAULT TRUE,
  "public_slug_scan_count" INTEGER NOT NULL DEFAULT 0,
  "public_slug_last_scan" TIMESTAMP(6) WITHOUT TIME ZONE,
  "published_at" TIMESTAMP(6) WITHOUT TIME ZONE,
  "expires_at" TIMESTAMP(6) WITHOUT TIME ZONE,
  "revision" INTEGER NOT NULL DEFAULT 1,
  "deleted_at" TIMESTAMP(6) WITHOUT TIME ZONE,
  "deleted_by" VARCHAR(100),
  "deleted_reason" TEXT,
  "created_by" BIGINT,
  "updated_by" BIGINT,
  "created_at" TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uk_slot_version" UNIQUE ("template_uuid", "norm", "nopen", "label", "version"),
  CONSTRAINT "uk_public_slug" UNIQUE ("public_slug"),
  CONSTRAINT "uniq_ezdoc_documents_uuid" UNIQUE ("uuid"),
  CONSTRAINT "fk_ezdoc_documents_template" FOREIGN KEY ("template_id") REFERENCES "ezdoc_templates" ("id") ON DELETE RESTRICT
);
COMMENT ON TABLE "ezdoc_documents" IS 'Document instances dari template dengan versioning + integrity + lifecycle';
COMMENT ON COLUMN "ezdoc_documents"."uuid" IS 'Stable UUID untuk API/external ref';
COMMENT ON COLUMN "ezdoc_documents"."template_id" IS 'FK ke specific template version (immutable)';
COMMENT ON COLUMN "ezdoc_documents"."template_uuid" IS 'Template family (denormalized untuk query cepat)';
COMMENT ON COLUMN "ezdoc_documents"."title" IS 'Human-readable name (auto-computed)';
COMMENT ON COLUMN "ezdoc_documents"."norm" IS 'No Rekam Medis (nullable untuk general scope)';
COMMENT ON COLUMN "ezdoc_documents"."nopen" IS 'No Pendaftaran (nullable untuk general scope)';
COMMENT ON COLUMN "ezdoc_documents"."label" IS 'Pembeda dokumen dalam slot';
COMMENT ON COLUMN "ezdoc_documents"."field_values" IS 'User-input field values';
COMMENT ON COLUMN "ezdoc_documents"."signature_values" IS 'Base64 signature images per TTD placeholder';
COMMENT ON COLUMN "ezdoc_documents"."metadata" IS 'Custom fields per-tenant tanpa migration';
COMMENT ON COLUMN "ezdoc_documents"."is_locked" IS 'Duplicate of status=locked untuk fast query';
COMMENT ON COLUMN "ezdoc_documents"."content_hash" IS 'SHA-256 canonical data';
COMMENT ON COLUMN "ezdoc_documents"."public_slug" IS 'Random slug untuk QR verify';
COMMENT ON COLUMN "ezdoc_documents"."public_slug_active" IS '0 = revoked';
COMMENT ON COLUMN "ezdoc_documents"."published_at" IS 'Waktu status = published';
COMMENT ON COLUMN "ezdoc_documents"."expires_at" IS 'Auto-expire timestamp (optional)';
COMMENT ON COLUMN "ezdoc_documents"."revision" IS 'Increment on each UPDATE';
COMMENT ON COLUMN "ezdoc_documents"."deleted_reason" IS 'Alasan delete untuk audit trail';
CREATE INDEX "idx_uuid" ON "ezdoc_documents" ("uuid");
CREATE INDEX "idx_template" ON "ezdoc_documents" ("template_id");
CREATE INDEX "idx_template_uuid" ON "ezdoc_documents" ("template_uuid");
CREATE INDEX "idx_norm_nopen" ON "ezdoc_documents" ("norm", "nopen");
CREATE INDEX "idx_status_deleted" ON "ezdoc_documents" ("status", "deleted_at");
CREATE INDEX "idx_slot" ON "ezdoc_documents" ("template_uuid", "norm", "nopen", "label", "deleted_at");
CREATE INDEX "idx_deleted" ON "ezdoc_documents" ("deleted_at");
CREATE INDEX "idx_expires" ON "ezdoc_documents" ("expires_at");
CREATE INDEX "idx_created_by" ON "ezdoc_documents" ("created_by", "created_at");
CREATE INDEX "idx_updated" ON "ezdoc_documents" ("updated_at");

-- Table: ezdoc_signatures
CREATE TABLE "ezdoc_signatures" (
  "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  "uuid" UUID NOT NULL,
  "document_id" BIGINT NOT NULL,
  "signature_id_within_doc" INTEGER NOT NULL DEFAULT 0,
  "signer_id" VARCHAR(128) NOT NULL,
  "signer_role" VARCHAR(64),
  "signer_user_id" BIGINT,
  "provider" VARCHAR(32) NOT NULL,
  "level" INTEGER NOT NULL,
  "envelope_format" VARCHAR(32) NOT NULL,
  "envelope" BYTEA NOT NULL,
  "content_hash" VARCHAR(64) NOT NULL,
  "content_hash_algo" VARCHAR(16) NOT NULL DEFAULT 'sha256',
  "certificate_pem" TEXT,
  "certificate_serial" VARCHAR(64),
  "certificate_subject" VARCHAR(255),
  "certificate_issuer" VARCHAR(255),
  "tsa_response" BYTEA,
  "signed_at" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
  "verified_at" TIMESTAMP(6) WITHOUT TIME ZONE,
  "verify_status" TEXT NOT NULL DEFAULT 'pending' CHECK ("verify_status" IN ('valid', 'tampered', 'expired', 'revoked', 'untrusted', 'error', 'pending')),
  "verify_reason" VARCHAR(255),
  "metadata" JSONB,
  "created_at" TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP(6) WITHOUT TIME ZONE,
  PRIMARY KEY ("id"),
  CONSTRAINT "uniq_ezdoc_signatures_uuid" UNIQUE ("uuid"),
  CONSTRAINT "fk_ezdoc_signatures_document" FOREIGN KEY ("document_id") REFERENCES "ezdoc_documents" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
COMMENT ON TABLE "ezdoc_signatures" IS 'Signature envelopes per document — L1 HMAC, L2 LocalPKI, L3 PSrE';
COMMENT ON COLUMN "ezdoc_signatures"."document_id" IS 'FK to ezdoc_documents.id';
COMMENT ON COLUMN "ezdoc_signatures"."signature_id_within_doc" IS '0..N for multi-signer docs';
COMMENT ON COLUMN "ezdoc_signatures"."signer_id" IS 'Opaque identity string (domain-agnostic)';
COMMENT ON COLUMN "ezdoc_signatures"."signer_role" IS 'Role at signing time (snapshot)';
COMMENT ON COLUMN "ezdoc_signatures"."signer_user_id" IS 'Consumer user id if available';
COMMENT ON COLUMN "ezdoc_signatures"."provider" IS 'hmac | local_pki | peruri | ...';
COMMENT ON COLUMN "ezdoc_signatures"."level" IS '1 | 2 | 3 (assurance level)';
COMMENT ON COLUMN "ezdoc_signatures"."envelope_format" IS 'hmac | raw | pkcs7 | pades';
COMMENT ON COLUMN "ezdoc_signatures"."envelope" IS 'Raw signature bytes';
COMMENT ON COLUMN "ezdoc_signatures"."content_hash" IS 'SHA-256 hex of signed content';
COMMENT ON COLUMN "ezdoc_signatures"."certificate_pem" IS 'Signer X.509 certificate (PEM)';
COMMENT ON COLUMN "ezdoc_signatures"."certificate_serial" IS 'For revocation check';
COMMENT ON COLUMN "ezdoc_signatures"."certificate_subject" IS 'Subject CN';
COMMENT ON COLUMN "ezdoc_signatures"."certificate_issuer" IS 'Issuer CN';
COMMENT ON COLUMN "ezdoc_signatures"."tsa_response" IS 'RFC 3161 timestamp token';
COMMENT ON COLUMN "ezdoc_signatures"."signed_at" IS 'Signature timestamp';
COMMENT ON COLUMN "ezdoc_signatures"."verified_at" IS 'Last verify time';
CREATE INDEX "idx_document" ON "ezdoc_signatures" ("document_id");
CREATE INDEX "idx_signer" ON "ezdoc_signatures" ("signer_id");
CREATE INDEX "idx_provider_level" ON "ezdoc_signatures" ("provider", "level");
CREATE INDEX "idx_signed_at" ON "ezdoc_signatures" ("signed_at");
CREATE INDEX "idx_verify_status" ON "ezdoc_signatures" ("verify_status");
CREATE INDEX "idx_cert_serial" ON "ezdoc_signatures" ("certificate_serial");

-- Table: ezdoc_templates
CREATE TABLE "ezdoc_templates" (
  "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  "uuid" UUID NOT NULL,
  "slug" VARCHAR(120) NOT NULL,
  "version" INTEGER NOT NULL DEFAULT 1,
  "is_current" BOOLEAN NOT NULL DEFAULT TRUE,
  "parent_version_id" BIGINT,
  "name" VARCHAR(255) NOT NULL,
  "category" VARCHAR(100) NOT NULL DEFAULT '',
  "scope" TEXT NOT NULL DEFAULT 'patient' CHECK ("scope" IN ('patient', 'general')),
  "content" TEXT,
  "content_hash" VARCHAR(64),
  "signature_config" JSONB,
  "layout_config" JSONB,
  "verify_config" JSONB,
  "access_config" JSONB,
  "metadata" JSONB,
  "owner_id" BIGINT,
  "is_active" BOOLEAN NOT NULL DEFAULT TRUE,
  "is_locked" BOOLEAN NOT NULL DEFAULT FALSE,
  "revision" INTEGER NOT NULL DEFAULT 1,
  "deleted_at" TIMESTAMP(6) WITHOUT TIME ZONE,
  "deleted_by" VARCHAR(100),
  "deleted_reason" TEXT,
  "created_by" BIGINT,
  "updated_by" BIGINT,
  "created_at" TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uk_uuid_version" UNIQUE ("uuid", "version"),
  CONSTRAINT "fk_ezdoc_templates_parent" FOREIGN KEY ("parent_version_id") REFERENCES "ezdoc_templates" ("id") ON DELETE SET NULL
);
COMMENT ON TABLE "ezdoc_templates" IS 'Template design storage dengan versioning + integrity check';
COMMENT ON COLUMN "ezdoc_templates"."uuid" IS 'Template family ID (UUID v7, same across versions)';
COMMENT ON COLUMN "ezdoc_templates"."slug" IS 'URL-friendly identifier (per family)';
COMMENT ON COLUMN "ezdoc_templates"."version" IS 'Version dalam family';
COMMENT ON COLUMN "ezdoc_templates"."is_current" IS '1 = active version untuk family';
COMMENT ON COLUMN "ezdoc_templates"."parent_version_id" IS 'Chain ke previous version';
COMMENT ON COLUMN "ezdoc_templates"."category" IS 'Kategori/folder pengelompokan';
COMMENT ON COLUMN "ezdoc_templates"."content" IS 'HTML template dari WYSIWYG editor';
COMMENT ON COLUMN "ezdoc_templates"."content_hash" IS 'SHA-256 canonical content+configs';
COMMENT ON COLUMN "ezdoc_templates"."signature_config" IS 'Config TTD placeholders';
COMMENT ON COLUMN "ezdoc_templates"."layout_config" IS 'Config logos, page size, padding';
COMMENT ON COLUMN "ezdoc_templates"."verify_config" IS 'Field mana yg tampil di verify page';
COMMENT ON COLUMN "ezdoc_templates"."access_config" IS 'RBAC per-template';
COMMENT ON COLUMN "ezdoc_templates"."metadata" IS 'Custom fields per-tenant tanpa migration';
COMMENT ON COLUMN "ezdoc_templates"."owner_id" IS 'ID pegawai/user creator';
COMMENT ON COLUMN "ezdoc_templates"."is_active" IS 'Soft-disable tanpa delete';
COMMENT ON COLUMN "ezdoc_templates"."is_locked" IS 'Prevent destructive field changes';
COMMENT ON COLUMN "ezdoc_templates"."revision" IS 'Increment on each UPDATE';
COMMENT ON COLUMN "ezdoc_templates"."deleted_reason" IS 'Alasan delete untuk audit trail';
CREATE INDEX "idx_uuid" ON "ezdoc_templates" ("uuid");
CREATE INDEX "idx_slug" ON "ezdoc_templates" ("slug");
CREATE INDEX "idx_current_active" ON "ezdoc_templates" ("is_current", "is_active", "deleted_at");
CREATE INDEX "idx_category" ON "ezdoc_templates" ("category");
CREATE INDEX "idx_scope" ON "ezdoc_templates" ("scope");
CREATE INDEX "idx_owner" ON "ezdoc_templates" ("owner_id");
CREATE INDEX "idx_parent" ON "ezdoc_templates" ("parent_version_id");
CREATE INDEX "idx_updated" ON "ezdoc_templates" ("updated_at");
