-- ezdoc-spec DDL: sqlite
-- Generated by ezdoc/cli/spec-dump.php from migrations/blueprints/
-- DO NOT EDIT — regenerate via `php cli/spec-dump.php`

-- Table: ezdoc_audit_log
CREATE TABLE "ezdoc_audit_log" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "event_type" VARCHAR(64) NOT NULL,
  "event_uuid" TEXT NULL,
  "actor_id" BIGINT NULL,
  "actor_roles" VARCHAR(255) NULL,
  "actor_type" TEXT NOT NULL DEFAULT 'user' CHECK ("actor_type" IN ('user', 'system', 'public', 'api')),
  "target_type" VARCHAR(32) NULL,
  "target_id" VARCHAR(64) NULL,
  "template_id" BIGINT NULL,
  "doc_id" BIGINT NULL,
  "ip_address" VARCHAR(45) NULL,
  "user_agent" TEXT NULL,
  "request_id" TEXT NULL,
  "session_id" VARCHAR(64) NULL,
  "trace_id" TEXT NULL,
  "previous_value" TEXT NULL CHECK ("previous_value" IS NULL OR json_valid("previous_value")),
  "new_value" TEXT NULL CHECK ("new_value" IS NULL OR json_valid("new_value")),
  "metadata" TEXT NULL CHECK ("metadata" IS NULL OR json_valid("metadata")),
  "result" TEXT NOT NULL DEFAULT 'success' CHECK ("result" IN ('success', 'denied', 'error', 'warning')),
  "message" TEXT NULL,
  "occurred_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "idx_event_time" ON "ezdoc_audit_log" ("event_type", "occurred_at");
CREATE INDEX "idx_actor_time" ON "ezdoc_audit_log" ("actor_id", "occurred_at");
CREATE INDEX "idx_target" ON "ezdoc_audit_log" ("target_type", "target_id");
CREATE INDEX "idx_template_time" ON "ezdoc_audit_log" ("template_id", "occurred_at");
CREATE INDEX "idx_doc_time" ON "ezdoc_audit_log" ("doc_id", "occurred_at");
CREATE INDEX "idx_time" ON "ezdoc_audit_log" ("occurred_at");
CREATE INDEX "idx_result_time" ON "ezdoc_audit_log" ("result", "occurred_at");
CREATE INDEX "idx_request" ON "ezdoc_audit_log" ("request_id");
CREATE INDEX "idx_session" ON "ezdoc_audit_log" ("session_id");
CREATE INDEX "idx_trace" ON "ezdoc_audit_log" ("trace_id");

-- Table: ezdoc_default_vars
CREATE TABLE "ezdoc_default_vars" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "var_name" VARCHAR(100) NOT NULL,
  "description" VARCHAR(255) NULL,
  "is_enabled" INTEGER NOT NULL DEFAULT 1,
  "metadata" TEXT NULL CHECK ("metadata" IS NULL OR json_valid("metadata")),
  "created_at" DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "uniq_ezdoc_default_vars_var_name" UNIQUE ("var_name")
);
CREATE INDEX "idx_enabled" ON "ezdoc_default_vars" ("is_enabled");

-- Table: ezdoc_documents
CREATE TABLE "ezdoc_documents" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "uuid" TEXT NOT NULL,
  "template_id" BIGINT NOT NULL,
  "template_uuid" TEXT NOT NULL,
  "template_version" INTEGER NOT NULL DEFAULT 1,
  "title" VARCHAR(255) NULL,
  "norm" VARCHAR(50) NULL,
  "nopen" VARCHAR(50) NULL,
  "label" VARCHAR(100) NOT NULL DEFAULT '-',
  "version" INTEGER NOT NULL DEFAULT 1,
  "field_values" TEXT NULL CHECK ("field_values" IS NULL OR json_valid("field_values")),
  "signature_values" TEXT NULL CHECK ("signature_values" IS NULL OR json_valid("signature_values")),
  "metadata" TEXT NULL CHECK ("metadata" IS NULL OR json_valid("metadata")),
  "status" TEXT NOT NULL DEFAULT 'published' CHECK ("status" IN ('draft', 'published', 'locked', 'archived')),
  "is_locked" INTEGER NOT NULL DEFAULT 0,
  "content_hash" VARCHAR(64) NULL,
  "content_hash_at" DATETIME NULL,
  "content_hash_version" INTEGER NULL,
  "public_slug" VARCHAR(32) NULL,
  "public_slug_active" INTEGER NOT NULL DEFAULT 1,
  "public_slug_scan_count" INTEGER NOT NULL DEFAULT 0,
  "public_slug_last_scan" DATETIME NULL,
  "published_at" DATETIME NULL,
  "expires_at" DATETIME NULL,
  "revision" INTEGER NOT NULL DEFAULT 1,
  "deleted_at" DATETIME NULL,
  "deleted_by" VARCHAR(100) NULL,
  "deleted_reason" TEXT NULL,
  "created_by" BIGINT NULL,
  "updated_by" BIGINT NULL,
  "created_at" DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "uk_slot_version" UNIQUE ("template_uuid", "norm", "nopen", "label", "version"),
  CONSTRAINT "uk_public_slug" UNIQUE ("public_slug"),
  CONSTRAINT "uniq_ezdoc_documents_uuid" UNIQUE ("uuid"),
  FOREIGN KEY ("template_id") REFERENCES "ezdoc_templates" ("id") ON DELETE RESTRICT
);
CREATE INDEX "idx_uuid" ON "ezdoc_documents" ("uuid");
CREATE INDEX "idx_template" ON "ezdoc_documents" ("template_id");
CREATE INDEX "idx_template_uuid" ON "ezdoc_documents" ("template_uuid");
CREATE INDEX "idx_norm_nopen" ON "ezdoc_documents" ("norm", "nopen");
CREATE INDEX "idx_status_deleted" ON "ezdoc_documents" ("status", "deleted_at");
CREATE INDEX "idx_slot" ON "ezdoc_documents" ("template_uuid", "norm", "nopen", "label", "deleted_at");
CREATE INDEX "idx_deleted" ON "ezdoc_documents" ("deleted_at");
CREATE INDEX "idx_expires" ON "ezdoc_documents" ("expires_at");
CREATE INDEX "idx_created_by" ON "ezdoc_documents" ("created_by", "created_at");
CREATE INDEX "idx_updated" ON "ezdoc_documents" ("updated_at");

-- Table: ezdoc_signatures
CREATE TABLE "ezdoc_signatures" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "uuid" TEXT NOT NULL,
  "document_id" BIGINT NOT NULL,
  "signature_id_within_doc" INTEGER NOT NULL DEFAULT 0,
  "signer_id" VARCHAR(128) NOT NULL,
  "signer_role" VARCHAR(64) NULL,
  "signer_user_id" BIGINT NULL,
  "provider" VARCHAR(32) NOT NULL,
  "level" INTEGER NOT NULL,
  "envelope_format" VARCHAR(32) NOT NULL,
  "envelope" BLOB NOT NULL,
  "content_hash" VARCHAR(64) NOT NULL,
  "content_hash_algo" VARCHAR(16) NOT NULL DEFAULT 'sha256',
  "certificate_pem" TEXT NULL,
  "certificate_serial" VARCHAR(64) NULL,
  "certificate_subject" VARCHAR(255) NULL,
  "certificate_issuer" VARCHAR(255) NULL,
  "tsa_response" BLOB NULL,
  "signed_at" DATETIME NOT NULL,
  "verified_at" DATETIME NULL,
  "verify_status" TEXT NOT NULL DEFAULT 'pending' CHECK ("verify_status" IN ('valid', 'tampered', 'expired', 'revoked', 'untrusted', 'error', 'pending')),
  "verify_reason" VARCHAR(255) NULL,
  "metadata" TEXT NULL CHECK ("metadata" IS NULL OR json_valid("metadata")),
  "created_at" DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" DATETIME NULL,
  CONSTRAINT "uniq_ezdoc_signatures_uuid" UNIQUE ("uuid"),
  FOREIGN KEY ("document_id") REFERENCES "ezdoc_documents" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX "idx_document" ON "ezdoc_signatures" ("document_id");
CREATE INDEX "idx_signer" ON "ezdoc_signatures" ("signer_id");
CREATE INDEX "idx_provider_level" ON "ezdoc_signatures" ("provider", "level");
CREATE INDEX "idx_signed_at" ON "ezdoc_signatures" ("signed_at");
CREATE INDEX "idx_verify_status" ON "ezdoc_signatures" ("verify_status");
CREATE INDEX "idx_cert_serial" ON "ezdoc_signatures" ("certificate_serial");

-- Table: ezdoc_templates
CREATE TABLE "ezdoc_templates" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "uuid" TEXT NOT NULL,
  "slug" VARCHAR(120) NOT NULL,
  "version" INTEGER NOT NULL DEFAULT 1,
  "is_current" INTEGER NOT NULL DEFAULT 1,
  "parent_version_id" BIGINT NULL,
  "name" VARCHAR(255) NOT NULL,
  "category" VARCHAR(100) NOT NULL DEFAULT '',
  "scope" TEXT NOT NULL DEFAULT 'patient' CHECK ("scope" IN ('patient', 'general')),
  "content" TEXT NULL,
  "content_hash" VARCHAR(64) NULL,
  "signature_config" TEXT NULL CHECK ("signature_config" IS NULL OR json_valid("signature_config")),
  "layout_config" TEXT NULL CHECK ("layout_config" IS NULL OR json_valid("layout_config")),
  "verify_config" TEXT NULL CHECK ("verify_config" IS NULL OR json_valid("verify_config")),
  "access_config" TEXT NULL CHECK ("access_config" IS NULL OR json_valid("access_config")),
  "metadata" TEXT NULL CHECK ("metadata" IS NULL OR json_valid("metadata")),
  "owner_id" BIGINT NULL,
  "is_active" INTEGER NOT NULL DEFAULT 1,
  "is_locked" INTEGER NOT NULL DEFAULT 0,
  "revision" INTEGER NOT NULL DEFAULT 1,
  "deleted_at" DATETIME NULL,
  "deleted_by" VARCHAR(100) NULL,
  "deleted_reason" TEXT NULL,
  "created_by" BIGINT NULL,
  "updated_by" BIGINT NULL,
  "created_at" DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "uk_uuid_version" UNIQUE ("uuid", "version"),
  FOREIGN KEY ("parent_version_id") REFERENCES "ezdoc_templates" ("id") ON DELETE SET NULL
);
CREATE INDEX "idx_uuid" ON "ezdoc_templates" ("uuid");
CREATE INDEX "idx_slug" ON "ezdoc_templates" ("slug");
CREATE INDEX "idx_current_active" ON "ezdoc_templates" ("is_current", "is_active", "deleted_at");
CREATE INDEX "idx_category" ON "ezdoc_templates" ("category");
CREATE INDEX "idx_scope" ON "ezdoc_templates" ("scope");
CREATE INDEX "idx_owner" ON "ezdoc_templates" ("owner_id");
CREATE INDEX "idx_parent" ON "ezdoc_templates" ("parent_version_id");
CREATE INDEX "idx_updated" ON "ezdoc_templates" ("updated_at");
