-- ezdoc-spec DDL: sqlserver
-- Generated by ezdoc/cli/spec-dump.php from migrations/blueprints/
-- DO NOT EDIT — regenerate via `php cli/spec-dump.php`

-- Table: ezdoc_audit_log
CREATE TABLE [ezdoc_audit_log] (
  [id] BIGINT NOT NULL IDENTITY(1,1),
  [event_type] NVARCHAR(64) NOT NULL,
  [event_uuid] UNIQUEIDENTIFIER NULL,
  [actor_id] BIGINT NULL,
  [actor_roles] NVARCHAR(255) NULL,
  [actor_type] NVARCHAR(255) NOT NULL DEFAULT 'user' CHECK ([actor_type] IN ('user', 'system', 'public', 'api')),
  [target_type] NVARCHAR(32) NULL,
  [target_id] NVARCHAR(64) NULL,
  [template_id] BIGINT NULL,
  [doc_id] BIGINT NULL,
  [ip_address] NVARCHAR(45) NULL,
  [user_agent] NVARCHAR(MAX) NULL,
  [request_id] UNIQUEIDENTIFIER NULL,
  [session_id] NVARCHAR(64) NULL,
  [trace_id] UNIQUEIDENTIFIER NULL,
  [previous_value] NVARCHAR(MAX) NULL CHECK ([previous_value] IS NULL OR ISJSON([previous_value]) = 1),
  [new_value] NVARCHAR(MAX) NULL CHECK ([new_value] IS NULL OR ISJSON([new_value]) = 1),
  [metadata] NVARCHAR(MAX) NULL CHECK ([metadata] IS NULL OR ISJSON([metadata]) = 1),
  [result] NVARCHAR(255) NOT NULL DEFAULT 'success' CHECK ([result] IN ('success', 'denied', 'error', 'warning')),
  [message] NVARCHAR(MAX) NULL,
  [occurred_at] DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT [pk_ezdoc_audit_log] PRIMARY KEY ([id])
);
CREATE INDEX [idx_event_time] ON [ezdoc_audit_log] ([event_type], [occurred_at]);
CREATE INDEX [idx_actor_time] ON [ezdoc_audit_log] ([actor_id], [occurred_at]);
CREATE INDEX [idx_target] ON [ezdoc_audit_log] ([target_type], [target_id]);
CREATE INDEX [idx_template_time] ON [ezdoc_audit_log] ([template_id], [occurred_at]);
CREATE INDEX [idx_doc_time] ON [ezdoc_audit_log] ([doc_id], [occurred_at]);
CREATE INDEX [idx_time] ON [ezdoc_audit_log] ([occurred_at]);
CREATE INDEX [idx_result_time] ON [ezdoc_audit_log] ([result], [occurred_at]);
CREATE INDEX [idx_request] ON [ezdoc_audit_log] ([request_id]);
CREATE INDEX [idx_session] ON [ezdoc_audit_log] ([session_id]);
CREATE INDEX [idx_trace] ON [ezdoc_audit_log] ([trace_id]);

-- Table: ezdoc_default_vars
CREATE TABLE [ezdoc_default_vars] (
  [id] BIGINT NOT NULL IDENTITY(1,1),
  [var_name] NVARCHAR(100) NOT NULL,
  [description] NVARCHAR(255) NULL,
  [is_enabled] BIT NOT NULL DEFAULT 1,
  [metadata] NVARCHAR(MAX) NULL CHECK ([metadata] IS NULL OR ISJSON([metadata]) = 1),
  [created_at] DATETIME2 NULL DEFAULT CURRENT_TIMESTAMP,
  [updated_at] DATETIME2 NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT [pk_ezdoc_default_vars] PRIMARY KEY ([id]),
  CONSTRAINT [uniq_ezdoc_default_vars_var_name] UNIQUE ([var_name])
);
CREATE INDEX [idx_enabled] ON [ezdoc_default_vars] ([is_enabled]);

-- Table: ezdoc_documents
CREATE TABLE [ezdoc_documents] (
  [id] BIGINT NOT NULL IDENTITY(1,1),
  [uuid] UNIQUEIDENTIFIER NOT NULL,
  [template_id] BIGINT NOT NULL,
  [template_uuid] UNIQUEIDENTIFIER NOT NULL,
  [template_version] INT NOT NULL DEFAULT 1,
  [title] NVARCHAR(255) NULL,
  [norm] NVARCHAR(50) NULL,
  [nopen] NVARCHAR(50) NULL,
  [label] NVARCHAR(100) NOT NULL DEFAULT '-',
  [version] INT NOT NULL DEFAULT 1,
  [field_values] NVARCHAR(MAX) NULL CHECK ([field_values] IS NULL OR ISJSON([field_values]) = 1),
  [signature_values] NVARCHAR(MAX) NULL CHECK ([signature_values] IS NULL OR ISJSON([signature_values]) = 1),
  [metadata] NVARCHAR(MAX) NULL CHECK ([metadata] IS NULL OR ISJSON([metadata]) = 1),
  [status] NVARCHAR(255) NOT NULL DEFAULT 'published' CHECK ([status] IN ('draft', 'published', 'locked', 'archived')),
  [is_locked] BIT NOT NULL DEFAULT 0,
  [content_hash] NVARCHAR(64) NULL,
  [content_hash_at] DATETIME2 NULL,
  [content_hash_version] INT NULL,
  [public_slug] NVARCHAR(32) NULL,
  [public_slug_active] BIT NOT NULL DEFAULT 1,
  [public_slug_scan_count] INT NOT NULL DEFAULT 0,
  [public_slug_last_scan] DATETIME2 NULL,
  [published_at] DATETIME2 NULL,
  [expires_at] DATETIME2 NULL,
  [revision] INT NOT NULL DEFAULT 1,
  [deleted_at] DATETIME2 NULL,
  [deleted_by] NVARCHAR(100) NULL,
  [deleted_reason] NVARCHAR(MAX) NULL,
  [created_by] BIGINT NULL,
  [updated_by] BIGINT NULL,
  [created_at] DATETIME2 NULL DEFAULT CURRENT_TIMESTAMP,
  [updated_at] DATETIME2 NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT [pk_ezdoc_documents] PRIMARY KEY ([id]),
  CONSTRAINT [uk_slot_version] UNIQUE ([template_uuid], [norm], [nopen], [label], [version]),
  CONSTRAINT [uk_public_slug] UNIQUE ([public_slug]),
  CONSTRAINT [uniq_ezdoc_documents_uuid] UNIQUE ([uuid]),
  CONSTRAINT [fk_ezdoc_documents_template] FOREIGN KEY ([template_id]) REFERENCES [ezdoc_templates] ([id]) ON DELETE RESTRICT
);
CREATE INDEX [idx_uuid] ON [ezdoc_documents] ([uuid]);
CREATE INDEX [idx_template] ON [ezdoc_documents] ([template_id]);
CREATE INDEX [idx_template_uuid] ON [ezdoc_documents] ([template_uuid]);
CREATE INDEX [idx_norm_nopen] ON [ezdoc_documents] ([norm], [nopen]);
CREATE INDEX [idx_status_deleted] ON [ezdoc_documents] ([status], [deleted_at]);
CREATE INDEX [idx_slot] ON [ezdoc_documents] ([template_uuid], [norm], [nopen], [label], [deleted_at]);
CREATE INDEX [idx_deleted] ON [ezdoc_documents] ([deleted_at]);
CREATE INDEX [idx_expires] ON [ezdoc_documents] ([expires_at]);
CREATE INDEX [idx_created_by] ON [ezdoc_documents] ([created_by], [created_at]);
CREATE INDEX [idx_updated] ON [ezdoc_documents] ([updated_at]);

-- Table: ezdoc_signatures
CREATE TABLE [ezdoc_signatures] (
  [id] BIGINT NOT NULL IDENTITY(1,1),
  [uuid] UNIQUEIDENTIFIER NOT NULL,
  [document_id] BIGINT NOT NULL,
  [signature_id_within_doc] INT NOT NULL DEFAULT 0,
  [signer_id] NVARCHAR(128) NOT NULL,
  [signer_role] NVARCHAR(64) NULL,
  [signer_user_id] BIGINT NULL,
  [provider] NVARCHAR(32) NOT NULL,
  [level] INT NOT NULL,
  [envelope_format] NVARCHAR(32) NOT NULL,
  [envelope] VARBINARY(MAX) NOT NULL,
  [content_hash] NVARCHAR(64) NOT NULL,
  [content_hash_algo] NVARCHAR(16) NOT NULL DEFAULT 'sha256',
  [certificate_pem] NVARCHAR(MAX) NULL,
  [certificate_serial] NVARCHAR(64) NULL,
  [certificate_subject] NVARCHAR(255) NULL,
  [certificate_issuer] NVARCHAR(255) NULL,
  [tsa_response] VARBINARY(MAX) NULL,
  [signed_at] DATETIME2 NOT NULL,
  [verified_at] DATETIME2 NULL,
  [verify_status] NVARCHAR(255) NOT NULL DEFAULT 'pending' CHECK ([verify_status] IN ('valid', 'tampered', 'expired', 'revoked', 'untrusted', 'error', 'pending')),
  [verify_reason] NVARCHAR(255) NULL,
  [metadata] NVARCHAR(MAX) NULL CHECK ([metadata] IS NULL OR ISJSON([metadata]) = 1),
  [created_at] DATETIME2 NULL DEFAULT CURRENT_TIMESTAMP,
  [updated_at] DATETIME2 NULL DEFAULT CURRENT_TIMESTAMP,
  [deleted_at] DATETIME2 NULL,
  CONSTRAINT [pk_ezdoc_signatures] PRIMARY KEY ([id]),
  CONSTRAINT [uniq_ezdoc_signatures_uuid] UNIQUE ([uuid]),
  CONSTRAINT [fk_ezdoc_signatures_document] FOREIGN KEY ([document_id]) REFERENCES [ezdoc_documents] ([id]) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX [idx_document] ON [ezdoc_signatures] ([document_id]);
CREATE INDEX [idx_signer] ON [ezdoc_signatures] ([signer_id]);
CREATE INDEX [idx_provider_level] ON [ezdoc_signatures] ([provider], [level]);
CREATE INDEX [idx_signed_at] ON [ezdoc_signatures] ([signed_at]);
CREATE INDEX [idx_verify_status] ON [ezdoc_signatures] ([verify_status]);
CREATE INDEX [idx_cert_serial] ON [ezdoc_signatures] ([certificate_serial]);

-- Table: ezdoc_templates
CREATE TABLE [ezdoc_templates] (
  [id] BIGINT NOT NULL IDENTITY(1,1),
  [uuid] UNIQUEIDENTIFIER NOT NULL,
  [slug] NVARCHAR(120) NOT NULL,
  [version] INT NOT NULL DEFAULT 1,
  [is_current] BIT NOT NULL DEFAULT 1,
  [parent_version_id] BIGINT NULL,
  [name] NVARCHAR(255) NOT NULL,
  [category] NVARCHAR(100) NOT NULL DEFAULT '',
  [scope] NVARCHAR(255) NOT NULL DEFAULT 'patient' CHECK ([scope] IN ('patient', 'general')),
  [content] NVARCHAR(MAX) NULL,
  [content_hash] NVARCHAR(64) NULL,
  [signature_config] NVARCHAR(MAX) NULL CHECK ([signature_config] IS NULL OR ISJSON([signature_config]) = 1),
  [layout_config] NVARCHAR(MAX) NULL CHECK ([layout_config] IS NULL OR ISJSON([layout_config]) = 1),
  [verify_config] NVARCHAR(MAX) NULL CHECK ([verify_config] IS NULL OR ISJSON([verify_config]) = 1),
  [access_config] NVARCHAR(MAX) NULL CHECK ([access_config] IS NULL OR ISJSON([access_config]) = 1),
  [metadata] NVARCHAR(MAX) NULL CHECK ([metadata] IS NULL OR ISJSON([metadata]) = 1),
  [owner_id] BIGINT NULL,
  [is_active] BIT NOT NULL DEFAULT 1,
  [is_locked] BIT NOT NULL DEFAULT 0,
  [revision] INT NOT NULL DEFAULT 1,
  [deleted_at] DATETIME2 NULL,
  [deleted_by] NVARCHAR(100) NULL,
  [deleted_reason] NVARCHAR(MAX) NULL,
  [created_by] BIGINT NULL,
  [updated_by] BIGINT NULL,
  [created_at] DATETIME2 NULL DEFAULT CURRENT_TIMESTAMP,
  [updated_at] DATETIME2 NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT [pk_ezdoc_templates] PRIMARY KEY ([id]),
  CONSTRAINT [uk_uuid_version] UNIQUE ([uuid], [version]),
  CONSTRAINT [fk_ezdoc_templates_parent] FOREIGN KEY ([parent_version_id]) REFERENCES [ezdoc_templates] ([id]) ON DELETE SET NULL
);
CREATE INDEX [idx_uuid] ON [ezdoc_templates] ([uuid]);
CREATE INDEX [idx_slug] ON [ezdoc_templates] ([slug]);
CREATE INDEX [idx_current_active] ON [ezdoc_templates] ([is_current], [is_active], [deleted_at]);
CREATE INDEX [idx_category] ON [ezdoc_templates] ([category]);
CREATE INDEX [idx_scope] ON [ezdoc_templates] ([scope]);
CREATE INDEX [idx_owner] ON [ezdoc_templates] ([owner_id]);
CREATE INDEX [idx_parent] ON [ezdoc_templates] ([parent_version_id]);
CREATE INDEX [idx_updated] ON [ezdoc_templates] ([updated_at]);
