<?php

declare(strict_types=1);

/**
 * cli/spec-dump.php — regenerate ezdoc-spec/ artifacts dari Blueprint sources.
 *
 * Read: migrations/blueprints/*.php (single source of truth)
 * Write:
 *   - ezdoc-spec/schema/tables.json + tables.yaml  (declarative descriptor)
 *   - ezdoc-spec/ddl/{mysql,mariadb,sqlite,postgres,sqlserver}.sql  (generated DDL per platform)
 *   - ezdoc-spec/meta/version.json + checksum.txt
 *
 * ## Modes
 *
 *   php cli/spec-dump.php           — Regenerate (overwrite)
 *   php cli/spec-dump.php --check   — Verify current spec matches source (CI gate);
 *                                     exit 1 kalau diff, exit 0 kalau clean
 *   php cli/spec-dump.php --help
 *
 * ## Cross-language consumption
 *
 * Go port: `yq eval schema/tables.yaml` → codegen struct
 * Rust port: `serde_yaml::from_str(schema/tables.yaml)` → struct
 * TypeScript port: `js-yaml` → interface
 *
 * Semua tidak perlu tahu apapun soal PHP-specific implementation.
 *
 * @implementation-notes Source-of-truth-first pattern mirroring Prisma
 *   `prisma generate` command dari schema.prisma. Reimplemented from spec.
 */

require_once __DIR__ . '/../autoload.php';

use Ezdoc\Db\Grammar\MysqlGrammar;
use Ezdoc\Db\Grammar\MariaDbGrammar;
use Ezdoc\Db\Grammar\SqliteGrammar;
use Ezdoc\Db\Grammar\PostgresGrammar;
use Ezdoc\Db\Grammar\SqlServerGrammar;
use Ezdoc\Db\Schema\Blueprint;

// ============================================================================
// Config
// ============================================================================

$rootDir      = dirname(__DIR__);
$blueprintDir = $rootDir . '/migrations/blueprints';
$specDir      = $rootDir . '/ezdoc-spec';
$ezdocVersion = '0.9.9-dev';

$grammars = [
    'mysql'     => new MysqlGrammar(),
    'mariadb'   => new MariaDbGrammar(),
    'sqlite'    => new SqliteGrammar(),
    'postgres'  => new PostgresGrammar(),
    'sqlserver' => new SqlServerGrammar(),
];

// ============================================================================
// CLI args
// ============================================================================

$argv = $_SERVER['argv'] ?? [];
$isCheck = in_array('--check', $argv, true);
$isHelp = in_array('--help', $argv, true) || in_array('-h', $argv, true);

if ($isHelp) {
    echo <<<HELP
Usage: php cli/spec-dump.php [--check] [--help]

Modes:
  (no args)   Regenerate ezdoc-spec/ artifacts dari Blueprint sources.
  --check     Verify current spec matches source. Exit 1 kalau diff.
              Digunakan CI gate untuk enforce spec always up-to-date.
  --help      Show this help.

HELP;
    exit(0);
}

// ============================================================================
// Load blueprints
// ============================================================================

if (!is_dir($blueprintDir)) {
    fwrite(STDERR, "Blueprint dir tidak ada: $blueprintDir\n");
    exit(2);
}

$blueprintFiles = glob($blueprintDir . '/*.php');
sort($blueprintFiles);
$blueprints = [];

foreach ($blueprintFiles as $file) {
    $bp = require $file;
    if (!$bp instanceof Blueprint) {
        fwrite(STDERR, "$file: harus return Blueprint instance\n");
        exit(2);
    }
    $blueprints[$bp->getName()] = $bp;
}

echo "Loaded " . count($blueprints) . " blueprints:\n";
foreach ($blueprints as $name => $_) echo "  - $name\n";

// ============================================================================
// Generate artifacts (in-memory first, write later untuk atomic + check mode)
// ============================================================================

$artifacts = [];

// 1) schema/tables.json + tables.yaml
$tablesArr = [];
foreach ($blueprints as $name => $bp) {
    $tablesArr[$name] = $bp->toArray();
}
$artifacts['schema/tables.json'] = json_encode($tablesArr, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n";
$artifacts['schema/tables.yaml'] = _ezdocToYaml($tablesArr);

// 2) ddl/*.sql per platform
foreach ($grammars as $platform => $grammar) {
    $sqls = [];
    $sqls[] = "-- ezdoc-spec DDL: $platform";
    $sqls[] = "-- Generated by ezdoc/cli/spec-dump.php from migrations/blueprints/";
    $sqls[] = "-- DO NOT EDIT — regenerate via `php cli/spec-dump.php`";
    $sqls[] = '';
    foreach ($blueprints as $name => $bp) {
        $sqls[] = "-- Table: $name";
        foreach ($grammar->compileCreateTable($bp) as $sql) {
            $sqls[] = $sql . ';';
        }
        $sqls[] = '';
    }
    $artifacts["ddl/$platform.sql"] = implode("\n", $sqls);
}

// 3) meta/version.json + checksum.txt
$checksum = hash('sha256', implode('|', array_map('md5', $artifacts)));
$artifacts['meta/version.json'] = json_encode([
    'ezdoc_version'  => $ezdocVersion,
    'spec_version'   => '1.0-draft',
    'generated_by'   => 'cli/spec-dump.php',
    'source'         => 'migrations/blueprints/',
    'grammars'       => array_keys($grammars),
    'table_count'    => count($blueprints),
    'checksum'       => $checksum,
], JSON_PRETTY_PRINT) . "\n";
$artifacts['meta/checksum.txt'] = $checksum . "\n";

// ============================================================================
// Check mode: verify current spec matches source
// ============================================================================

if ($isCheck) {
    $mismatches = [];
    foreach ($artifacts as $path => $expected) {
        $full = $specDir . '/' . $path;
        if (!file_exists($full)) {
            $mismatches[] = "$path (missing)";
            continue;
        }
        $actual = file_get_contents($full);
        if ($actual !== $expected) {
            $mismatches[] = "$path (out-of-date)";
        }
    }
    if ($mismatches !== []) {
        fwrite(STDERR, "\nERROR: Spec out-of-date. Run `php cli/spec-dump.php` to regenerate.\n");
        fwrite(STDERR, "   Files needing update:\n");
        foreach ($mismatches as $m) fwrite(STDERR, "     - $m\n");
        exit(1);
    }
    echo "\n✓ ezdoc-spec/ up-to-date with source blueprints.\n";
    exit(0);
}

// ============================================================================
// Write mode: atomic write ke spec dir
// ============================================================================

echo "\nWriting artifacts ke $specDir/\n";
foreach ($artifacts as $path => $content) {
    $full = $specDir . '/' . $path;
    $dir = dirname($full);
    if (!is_dir($dir)) {
        if (!mkdir($dir, 0755, true) && !is_dir($dir)) {
            fwrite(STDERR, "Failed create dir: $dir\n");
            exit(2);
        }
    }
    file_put_contents($full, $content);
    echo "  wrote  $path (" . strlen($content) . " bytes)\n";
}

// Add README for spec dir
$readme = <<<MD
# ezdoc-spec (generated)

**DO NOT EDIT MANUALLY.** Regenerate via `php cli/spec-dump.php` dari
project root.

Source of truth: `migrations/blueprints/*.php` (PHP Blueprint DSL).

## Contents

- `schema/tables.{json,yaml}` — DB schema descriptor (portable, cross-language)
- `ddl/*.sql` — Generated DDL per platform (mysql/mariadb/sqlite/postgres/sqlserver)
- `meta/version.json` — Version metadata + checksum
- `meta/checksum.txt` — SHA-256 hash of all artifacts (CI gate)

## Cross-language consumption

- **Go**: `yq eval schema/tables.yaml` → codegen struct
- **Rust**: `serde_yaml::from_str()` → struct + Diesel/SeaORM binding
- **TypeScript**: `js-yaml` → interface / Prisma / Drizzle schema

## CI gate

Add to CI pipeline:

```yaml
- run: php cli/spec-dump.php --check   # fail if spec out-of-date
```

MD;
file_put_contents($specDir . '/README.md', $readme);
echo "  wrote  README.md\n";

echo "\n✓ Spec regenerated. Checksum: " . substr($checksum, 0, 16) . "…\n";
echo "  Tables:   " . count($blueprints) . "\n";
echo "  Grammars: " . count($grammars) . "\n";
echo "  Version:  $ezdocVersion\n";

// ============================================================================
// Minimal YAML emitter (no external dep)
// ============================================================================

/**
 * Minimal YAML emitter untuk associative arrays.
 * Cukup untuk kebutuhan spec-dump — no fancy features (anchors, refs, dsb).
 * Kalau butuh lebih rich, install symfony/yaml (optional dev dep).
 */
function _ezdocToYaml($data, int $indent = 0): string
{
    $pad = str_repeat('  ', $indent);
    $out = '';

    if (is_array($data)) {
        // Detect associative vs list
        $isList = array_keys($data) === range(0, count($data) - 1);
        if ($data === []) return $pad === '' ? "{}\n" : "{}";

        if ($isList) {
            foreach ($data as $item) {
                if (is_array($item)) {
                    $out .= "$pad- \n" . _ezdocToYaml($item, $indent + 1);
                } else {
                    $out .= "$pad- " . _ezdocYamlScalar($item) . "\n";
                }
            }
        } else {
            foreach ($data as $key => $val) {
                if (is_array($val)) {
                    if ($val === []) {
                        $out .= "$pad$key: {}\n";
                    } else {
                        $out .= "$pad$key:\n" . _ezdocToYaml($val, $indent + 1);
                    }
                } else {
                    $out .= "$pad$key: " . _ezdocYamlScalar($val) . "\n";
                }
            }
        }
        return $out;
    }
    return _ezdocYamlScalar($data);
}

function _ezdocYamlScalar($v): string
{
    if ($v === null) return 'null';
    if (is_bool($v)) return $v ? 'true' : 'false';
    if (is_int($v) || is_float($v)) return (string) $v;
    $s = (string) $v;
    // Quote kalau ada karakter special
    if (preg_match('/[:#\[\]{}&*!|>%@`\'"\n\r]/', $s)
        || preg_match('/^\s|\s$/', $s)
        || in_array(strtolower($s), ['null', 'true', 'false', 'yes', 'no', '~'], true)
        || is_numeric($s)
    ) {
        return "'" . str_replace("'", "''", $s) . "'";
    }
    return $s;
}
